export const strings = {
  en: {
    eyebrow: "Free, 4-minute quiz",
    headline: "Is your hagwon's safety and communication as good as parents assume?",
    body: "A free 4-minute check across parent communication, safety, and five other areas — get your score and see what can be fixed today.",
    cta: "See your score",
    questionOf: (current: number, total: number) => `Question ${current} of ${total}`,
    noneMatchHint: "None of these quite fit? Pick the closest and tell us more at the end.",
    back: "Back",
    backHome: "Back to home",
    yourResult: "Your result",
    outOf: "out of 84",
    weakestPillarLabel: "Your weakest pillar",
    allPillars: "All seven pillars",
    leadIn: "Want the full breakdown in your inbox — with the steps to raise your score? Leave your info and I'll send it over and follow up directly.",
    disclaimer: "This is a quick gut-check based on patterns we see across hagwons, not a formal audit.",
    youMentioned: (answerText: string) => `You mentioned: "${answerText}" — `,
    // Only Parent Communication & Reporting has a shipped product answer
    // (Chekki Schools) — every other pillar routes to a call instead of a
    // product pitch, so the CTA never claims something that doesn't exist yet.
    closingSchools: (pillarName: string) =>
      `Chekki Schools — automated class reports with Korean translation built in — would close most of this ${pillarName} gap.`,
    closingHomework:
      "Chekki's homework helper personalizes practice per student — deterministic, not generic AI guesses — and ties every assignment back to what your teachers actually gave. As a partner school, you'd be introducing this directly to your parents.",
    closingOther: (pillarName: string) =>
      `This is common, and it's usually worth a closer look at your ${pillarName} specifically before deciding what to fix first.`,
    strongNote: "Solid — this one's already working, so focus your energy elsewhere first.",
    ctaTry: "Try Chekki",
    ctaTryCaption: "See how Chekki can help",
    ctaBook: "Book a meeting",
    ctaBookCaption: (pillarName: string) => `Let's discuss your ${pillarName} further`,
    ctaBookBody: (score: number) => `Hi, following my AI Readiness result (${score}/84), I'd like to set up a time to discuss my weakest pillar and next steps.`,
    namePlaceholder: "Your name",
    hagwonPlaceholder: "Hagwon name",
    emailPlaceholder: "Email (for your report)",
    contactPlaceholder: "Phone or KakaoTalk ID (optional)",
    feedbackPlaceholder: "Any of the questions not fit your situation? Tell us here (optional)",
    submitBtn: "Email me the full report",
    submittingBtn: "Sending...",
    thanks: "Thanks — check your inbox for the full report, and I'll follow up directly.",
    permalinkLabel: "Bookmark this link to come back to your report anytime:",
    emailError: "That email address doesn't look right — check it and try again.",
    rateLimitError: "Too many submissions from this connection — please try again in a few minutes.",
    noResultsTitle: "No results found",
    noResultsBody: "Looks like you haven't taken the assessment yet, or your answers expired.",
    takeAssessment: "Take the assessment",
  },
  ko: {
    eyebrow: "무료 4분 진단",
    headline: "우리 학원의 안전과 소통, 학부모님이 생각하는 만큼 잘 되고 있을까요?",
    body: "학부모 소통, 안전 등 7가지 영역을 4분 만에 무료로 점검해보세요. 점수를 확인하고 오늘 바로 고칠 점을 알아보세요.",
    cta: "내 점수 확인하기",
    questionOf: (current: number, total: number) => `${total}문항 중 ${current}번째`,
    noneMatchHint: "딱 맞는 보기가 없으신가요? 가장 가까운 항목을 고르시고, 마지막에 자세히 알려주세요.",
    back: "이전",
    backHome: "홈으로",
    yourResult: "결과",
    outOf: "84점 만점",
    weakestPillarLabel: "가장 취약한 영역",
    allPillars: "7개 영역 전체 결과",
    leadIn: "전체 리포트와 함께, 점수를 올릴 수 있는 구체적인 방법도 함께 안내해 드릴까요? 연락처를 남겨주시면 리포트를 보내드리고 직접 연락드리겠습니다.",
    disclaimer: "여러 학원에서 반복적으로 나타나는 패턴을 바탕으로 한 간단한 진단이며, 정식 컨설팅 리포트는 아닙니다.",
    youMentioned: (answerText: string) => `이렇게 답변해 주셨죠: "${answerText}" — `,
    closingSchools: (pillarName: string) =>
      `Chekki Schools — 자동 리포트 생성과 한국어 번역까지 지원합니다 — 를 활용하면 ${pillarName} 영역의 격차 대부분을 줄일 수 있습니다.`,
    closingHomework:
      "Chekki의 숙제 도우미는 학생별 맞춤 연습을 제공합니다 — 임의의 AI 추측이 아니라, 선생님이 실제로 낸 과제를 기반으로 한 결정론적 방식입니다. 파트너 학원으로서 학부모님들께 직접 소개하실 수 있습니다.",
    closingOther: (pillarName: string) =>
      `많은 학원들이 겪는 부분이며, ${pillarName} 영역을 자세히 살펴본 후 무엇부터 손볼지 정하시는 걸 추천드립니다.`,
    strongNote: "탄탄합니다 — 지금은 다른 영역에 집중하셔도 좋습니다.",
    ctaTry: "Chekki 사용해보기",
    ctaTryCaption: "Chekki가 어떻게 도움이 되는지 확인해보세요",
    ctaBook: "미팅 예약하기",
    ctaBookCaption: (pillarName: string) => `${pillarName}에 대해 더 자세히 이야기해보아요`,
    ctaBookBody: (score: number) => `안녕하세요, AI 준비도 진단 결과(${score}/84)를 확인했습니다. 가장 취약한 영역과 다음 단계에 대해 상담하고 싶습니다.`,
    namePlaceholder: "이름",
    hagwonPlaceholder: "학원 이름",
    emailPlaceholder: "이메일 (리포트 발송용)",
    contactPlaceholder: "전화번호 또는 카카오톡 아이디 (선택)",
    feedbackPlaceholder: "해당하는 보기가 없었던 질문이 있었나요? 자유롭게 알려주세요 (선택)",
    submitBtn: "전체 리포트 받기",
    submittingBtn: "전송 중...",
    thanks: "감사합니다 — 메일함에서 전체 리포트를 확인해주세요. 곧 직접 연락드리겠습니다.",
    permalinkLabel: "아래 링크를 저장해두시면 언제든 리포트를 다시 확인하실 수 있습니다:",
    emailError: "이메일 주소를 다시 확인해주세요.",
    rateLimitError: "잠시 후 다시 시도해주세요. 짧은 시간에 너무 많은 요청이 있었습니다.",
    noResultsTitle: "결과를 찾을 수 없습니다",
    noResultsBody: "아직 진단을 시작하지 않으셨거나, 저장된 답변이 만료된 것 같습니다.",
    takeAssessment: "진단 시작하기",
  },
} as const;
