export const strings = {
  en: {
    eyebrow: "Free, 4-minute quiz",
    headline: "How much of your hagwon still runs by hand?",
    body: "A quick check on parent updates, attendance, and teaching. Get your score and the first thing to fix.",
    cta: "Start the quiz",
    questionOf: (current: number, total: number) => `Question ${current} of ${total}`,
    noneMatchHint: "None of these quite fit? Pick the closest and tell us more at the end.",
    yourResult: "Your result",
    outOf: "out of 72",
    weakestPillarLabel: "Your weakest pillar",
    allPillars: "All seven pillars",
    chekkiFitIntro:
      "Chekki's product already covers three of these seven pillars today — parent communication, teaching personalization, and data. The rest are gaps most hagwon software doesn't touch either, and we're open to talking about closing them.",
    leadIn: "Want the full breakdown in your inbox? Leave your info and I'll send it over and follow up directly.",
    namePlaceholder: "Your name",
    hagwonPlaceholder: "Hagwon name",
    emailPlaceholder: "Email (for your report)",
    contactPlaceholder: "Phone or KakaoTalk ID (optional)",
    feedbackPlaceholder: "Any of the questions not fit your situation? Tell us here (optional)",
    submitBtn: "Email me the full report",
    thanks: "Thanks — check your inbox for the full report, and I'll follow up directly.",
    emailError: "That email address doesn't look right — check it and try again.",
    rateLimitError: "Too many submissions from this connection — please try again in a few minutes.",
    noResultsTitle: "No results found",
    noResultsBody: "Looks like you haven't taken the assessment yet, or your answers expired.",
    takeAssessment: "Take the assessment",
  },
  ko: {
    eyebrow: "무료 4분 진단",
    headline: "우리 학원, 아직 수작업으로 돌아가고 있지 않나요?",
    body: "학부모 소통, 출결, 수업 방식을 4분 만에 점검해보세요. 점수와 가장 먼저 고칠 점을 알려드립니다.",
    cta: "진단 시작하기",
    questionOf: (current: number, total: number) => `${total}문항 중 ${current}번째`,
    noneMatchHint: "딱 맞는 보기가 없으신가요? 가장 가까운 항목을 고르시고, 마지막에 자세히 알려주세요.",
    yourResult: "결과",
    outOf: "72점 만점",
    weakestPillarLabel: "가장 취약한 영역",
    allPillars: "7개 영역 전체 결과",
    chekkiFitIntro:
      "Chekki는 이미 7개 영역 중 3개 — 학부모 소통, 맞춤형 수업, 데이터 관리 — 를 제품으로 다루고 있습니다. 나머지는 대부분의 학원 소프트웨어도 다루지 않는 영역으로, 필요하시다면 함께 해결 방법을 논의할 수 있습니다.",
    leadIn: "전체 리포트를 메일로 받아보시겠어요? 연락처를 남겨주시면 리포트를 보내드리고 직접 연락드리겠습니다.",
    namePlaceholder: "이름",
    hagwonPlaceholder: "학원 이름",
    emailPlaceholder: "이메일 (리포트 발송용)",
    contactPlaceholder: "전화번호 또는 카카오톡 아이디 (선택)",
    feedbackPlaceholder: "해당하는 보기가 없었던 질문이 있었나요? 자유롭게 알려주세요 (선택)",
    submitBtn: "전체 리포트 받기",
    thanks: "감사합니다 — 메일함에서 전체 리포트를 확인해주세요. 곧 직접 연락드리겠습니다.",
    emailError: "이메일 주소를 다시 확인해주세요.",
    rateLimitError: "잠시 후 다시 시도해주세요. 짧은 시간에 너무 많은 요청이 있었습니다.",
    noResultsTitle: "결과를 찾을 수 없습니다",
    noResultsBody: "아직 진단을 시작하지 않으셨거나, 저장된 답변이 만료된 것 같습니다.",
    takeAssessment: "진단 시작하기",
  },
} as const;
