export const strings = {
  en: {
    eyebrow: "Free, 4-minute quiz",
    headline: "Is your hagwon's safety and communication as good as parents assume?",
    body: "A free 4-minute check across parent communication, safety, and five other areas — get your score and see what can be fixed today.",
    cta: "See your score",
    questionOf: (current: number, total: number) => `Question ${current} of ${total}`,
    noneMatchHint: "None of these quite fit? Pick the closest and tell us more at the end.",
    back: "Back",
    backHome: "Back to home",
    yourResult: "Your result",
    outOf: "out of 72",
    weakestPillarLabel: "Your weakest pillar",
    allPillars: "All seven pillars",
    leadIn: "Want the full breakdown in your inbox — with the steps to raise your score? Leave your info and I'll send it over and follow up directly.",
    disclaimer: "This is a quick gut-check based on patterns we see across hagwons, not a formal audit.",
    youMentioned: (answerText: string) => `You mentioned: "${answerText}" — `,
    closingQuestion: (hook: string, pillarName: string) =>
      `Chekki's ${hook} would close most of this ${pillarName} gap early — want to see how that works, or would a deeper audit make more sense first?`,
    ctaProducts: "Show me Chekki's products",
    ctaAudit: "Request a deeper audit",
    ctaProductsBody: (score: number) => `Hi, following my AI Readiness result (${score}/72), I'd like to see how Chekki's existing products can help.`,
    ctaAuditBody: (score: number) => `Hi, following my AI Readiness result (${score}/72), I'd like to set up a deeper audit to identify areas of improvement.`,
    namePlaceholder: "Your name",
    hagwonPlaceholder: "Hagwon name",
    emailPlaceholder: "Email (for your report)",
    contactPlaceholder: "Phone or KakaoTalk ID (optional)",
    feedbackPlaceholder: "Any of the questions not fit your situation? Tell us here (optional)",
    submitBtn: "Email me the full report",
    submittingBtn: "Sending...",
    thanks: "Thanks — check your inbox for the full report, and I'll follow up directly.",
    emailError: "That email address doesn't look right — check it and try again.",
    rateLimitError: "Too many submissions from this connection — please try again in a few minutes.",
    noResultsTitle: "No results found",
    noResultsBody: "Looks like you haven't taken the assessment yet, or your answers expired.",
    takeAssessment: "Take the assessment",
  },
  ko: {
    eyebrow: "무료 4분 진단",
    headline: "우리 학원의 안전과 소통, 학부모님이 생각하는 만큼 잘 되고 있을까요?",
    body: "학부모 소통, 안전 등 7가지 영역을 4분 만에 무료로 점검해보세요. 점수를 확인하고 오늘 바로 고칠 점을 알아보세요.",
    cta: "내 점수 확인하기",
    questionOf: (current: number, total: number) => `${total}문항 중 ${current}번째`,
    noneMatchHint: "딱 맞는 보기가 없으신가요? 가장 가까운 항목을 고르시고, 마지막에 자세히 알려주세요.",
    back: "이전",
    backHome: "홈으로",
    yourResult: "결과",
    outOf: "72점 만점",
    weakestPillarLabel: "가장 취약한 영역",
    allPillars: "7개 영역 전체 결과",
    leadIn: "전체 리포트와 함께, 점수를 올릴 수 있는 구체적인 방법도 함께 안내해 드릴까요? 연락처를 남겨주시면 리포트를 보내드리고 직접 연락드리겠습니다.",
    disclaimer: "학원들에게서 반복적으로 나타나는 패턴을 바탕으로 한 간단한 진단이며, 정식 컨설팅 리포트는 아닙니다.",
    youMentioned: (answerText: string) => `이렇게 답변해 주셨죠: "${answerText}" — `,
    closingQuestion: (hook: string, pillarName: string) =>
      `Chekki의 ${hook} 기능을 활용하면 ${pillarName} 영역의 격차 대부분을 초기에 줄일 수 있습니다 — 어떻게 작동하는지 살펴보시겠어요, 아니면 심층 진단이 먼저 필요하실까요?`,
    ctaProducts: "Chekki 제품 살펴보기",
    ctaAudit: "심층 진단 요청하기",
    ctaProductsBody: (score: number) => `안녕하세요, AI 준비도 진단 결과(${score}/72)를 확인했습니다. Chekki의 기존 제품이 어떻게 도움이 될 수 있는지 안내받고 싶습니다.`,
    ctaAuditBody: (score: number) => `안녕하세요, AI 준비도 진단 결과(${score}/72)를 확인했습니다. 개선점을 자세히 짚어보는 심층 진단을 요청하고 싶습니다.`,
    namePlaceholder: "이름",
    hagwonPlaceholder: "학원 이름",
    emailPlaceholder: "이메일 (리포트 발송용)",
    contactPlaceholder: "전화번호 또는 카카오톡 아이디 (선택)",
    feedbackPlaceholder: "해당하는 보기가 없었던 질문이 있었나요? 자유롭게 알려주세요 (선택)",
    submitBtn: "전체 리포트 받기",
    submittingBtn: "전송 중...",
    thanks: "감사합니다 — 메일함에서 전체 리포트를 확인해주세요. 곧 직접 연락드리겠습니다.",
    emailError: "이메일 주소를 다시 확인해주세요.",
    rateLimitError: "잠시 후 다시 시도해주세요. 짧은 시간에 너무 많은 요청이 있었습니다.",
    noResultsTitle: "결과를 찾을 수 없습니다",
    noResultsBody: "아직 진단을 시작하지 않으셨거나, 저장된 답변이 만료된 것 같습니다.",
    takeAssessment: "진단 시작하기",
  },
} as const;
